### ISSUE TITLE
Implement a 'type' command mapping

### ISSUE THREAD

**Issue by msmushmoon** [theia-jane/kree#1]
This should work something like:

```yaml
global:
    Super+i:
        config:
            actionType: keyPress 
        Shift+a: ä
        Shift+o: ö
```
Where pressing the sequence `Super+i`, `Shift+a` will 'type' `ä`
This is a non-trivial addition and will require major refactoring of the existing system.
