### ISSUE TITLE
Add a repeat command

### ISSUE THREAD

**Issue by msmushmoon** [theia-jane/kree#4]
The basic idea is that sometimes I want to repeat the last command I executed. This can be a little cumbersome if the key sequence is deep. For me, increasing my backlight involves `Super+; b k`. Repeating that 3 times is a pain in the neck. What I would like to have instead would be something like:

- `Super+k b k`
- `Super+.`
- `Super+.`

To acheive the same thing. Storing the most recent command should be trivial. My idea for the config file look something like:

```yaml
global:
  Super+Semicolon:
    b: 
      k: xbaclight -inc 5
  Super+Period: :!repeat-last
```

Where `:!` would be used to indicate a built-in kree command and `repeat-last` would indicate

to re-run the last command.
