### ISSUE TITLE
Add environment variables for commands

### ISSUE THREAD

**Issue by msmushmoon** [theia-jane/kree#5]
I don't have a solid usecase for this, yet. I have been thinking about ways to add context to the commands being run. My basic idea is that it would be useful to make environment variables available when executing a command. One such variable might be 'application name' like `firefox` or something. Basically, it would be useful to have some indication / conditional behavior of when and where the command was executed. 

This could look like:
```yaml

global: 
  Super+Semicolon:
    x: notify-send "Hello from ${KREE_APPLICATION}"
```

If executed in firefox it will display the message `Hello from firefox`. Not sold on the `KREE_` prefixed naming convention, but something like it to avoid collisions.
